
-- BEGIN: RAW.FIREHOSE

DELETE FROM RAW.FIREHOSE.AB_TEST_TRACK as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.EVENT:data:user_key = d.user_id
AND s.EVENT:data:user_key_type_id = 1;

DELETE FROM RAW.FIREHOSE.ITEM_SESSION as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.EVENT:data:user_id = d.user_id;

DELETE FROM RAW.FIREHOSE.PINPOINT as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.EVENT:endpoint:User:UserId::int = d.user_id;

DELETE FROM RAW.FIREHOSE.PREMIUM_SUBSCRIPTION_CREATED as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.EVENT:data:user_id = d.user_id;

DELETE FROM RAW.FIREHOSE.PREMIUM_SUBSCRIPTION_ENDED as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.EVENT:data:user_id = d.user_id;

DELETE FROM RAW.FIREHOSE.PREMIUM_SUBSCRIPTION_RENEWED as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.EVENT:data:user_id = d.user_id;

DELETE FROM RAW.FIREHOSE.SENDGRID_EVENTS as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_EMAILS as d
WHERE s.EVENT:email = d.email;

-- TODO: UNIFIED_EVENT_ALL (If this is not used, can we drop all data and stop the Snowpipe from loading new data?)

DELETE FROM RAW.FIREHOSE.USER_ACTION as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.EVENT:data:user_id = d.user_id;

DELETE FROM RAW.FIREHOSE.USER_ITEM_TAGS_ADDED as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.EVENT:data:user_id = d.user_id;

DELETE FROM RAW.FIREHOSE.USER_LIST_ITEM_CREATED as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.EVENT:data:user_id = d.user_id;

DELETE FROM RAW.FIREHOSE.USER_TRACK_ADV as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.EVENT:data:user_id = d.user_id;

DELETE FROM RAW.FIREHOSE.WEB_TRACK as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.EVENT:data:user_id = d.user_id;
