
-- BEGIN: LEARNING

DELETE FROM LEARNING.AIRFLOW.LIST as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.user_id = d.user_id;

DELETE FROM LEARNING.DEV.ANDROID_INLIST as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.user_id = d.user_id;

DELETE FROM LEARNING.DEV.PERSONALIZATION_USERS as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.user_id = d.user_id;

DELETE FROM LEARNING.DEV.PERSONALIZATION_USERS_V2 as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.user_id = d.user_id;

DELETE FROM LEARNING.MAML_COMMUNITY.LIST_ITEM_ENGAGEMENTS as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.user_id = d.user_id;

DELETE FROM LEARNING.MAML_COMMUNITY.LIST_ITEM_TAGS as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.user_id = d.user_id;

DELETE FROM LEARNING.MAML_COMMUNITY.USER_SAVES as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.user_id = d.user_id
or s.hashed_user_id = d.hashed_user_id;

DELETE FROM LEARNING.MAML_COMMUNITY.USER_SAVES_EXPORT as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.hashed_user_id = d.hashed_user_id;

DELETE FROM LEARNING.MAML_COMMUNITY.USER_SAVES_EXPORT_PARQUET as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.hashed_user_id = d.hashed_user_id;

--
-- BEGIN: SNAPSHOT.REDSHIFT

-- ACTION_TYPE -- no user_id or email data

-- API_USERS -- no user_id or email data

-- CAMPAIGN  -- no user_id or email data

DELETE FROM SNAPSHOT.REDSHIFT.HASHED_USER_ID_MAPPING as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.user_id = d.user_id
or s.hashed_user_id = d.hashed_user_id;

-- LEGACY_AD_CREATIVE_METADATA  -- no user_id or email data

-- LEGACY_AD_METADATA  -- no user_id or email data

-- MOZILLA_ACTIVITY_STREAM_DAILY_UNIQUES  -- no user_id or email data

-- MOZILLA_ACTIVITY_STREAM_DAILY_UNIQUES_DE  -- no user_id or email data

-- MOZILLA_ACTIVITY_STREAM_DAILY_UNIQUES_UK  -- no user_id or email data

-- MOZILLA_ACTIVITY_STREAM_IMPRESSION_STATS  -- no user_id or email data

-- MOZILLA_ACTIVITY_STREAM_IMPRESSION_STATS_BY_COUNTRY  -- no user_id or email data

-- MOZILLA_ACTIVITY_STREAM_MONTHLY_UNIQUES  -- no user_id or email data

-- MOZILLA_ACTIVITY_STREAM_PREFS  -- no user_id or email data

-- MOZILLA_ACTIVITY_STREAM_SPOC_FILL  -- no user_id or email data

-- NEWSLETTER_SUBSCRIBERS  -- no user_id or email data

-- PAYMENT_PRODUCTS  -- no user_id or email data

DELETE FROM SNAPSHOT.REDSHIFT.PAYMENT_SUBSCRIPTIONS as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.user_id = d.user_id;

-- Deleting based on both user_id and email
DELETE FROM SNAPSHOT.REDSHIFT.PH_EMAIL_V2_20220418_MIGRATION_ANNOUNCEMENT as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.user_id = d.user_id;

DELETE FROM SNAPSHOT.REDSHIFT.PH_EMAIL_V2_20220418_MIGRATION_ANNOUNCEMENT as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_EMAILS as d
WHERE s.email = d.email;

-- POCKET_HITS_CONTENT  -- no user_id or email data

-- POCKET_HITS_EMAIL  -- no user_id or email data

-- PUBWISE_GOOGLE_ADX_DAILY -- no user_id or email data

-- PUBWISE_GOOGLE_AD_MANAGER_DAILY -- no user_id or email data

-- PUBWISE_GOOGLE_ANALYTICS_DAILY -- no user_id or email data

-- PUBWISE_HEADER_BIDDING_REQUESTS_HOURLY -- no user_id or email data

-- PUBWISE_HEADER_BIDDING_WINS_HOURLY -- no user_id or email data

-- RESOLVED_ITEM_IDS_20220124 -- no user_id or email data

DELETE FROM SNAPSHOT.REDSHIFT.SENDGRID_SUPPRESSION_BLOCKS as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_EMAILS as d
WHERE s.email = d.email;

DELETE FROM SNAPSHOT.REDSHIFT.SENDGRID_SUPPRESSION_BOUNCES as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_EMAILS as d
WHERE s.email = d.email;

DELETE FROM SNAPSHOT.REDSHIFT.SENDGRID_SUPPRESSION_INVALID_EMAILS as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_EMAILS as d
WHERE s.email = d.email;

DELETE FROM SNAPSHOT.REDSHIFT.SENDGRID_SUPPRESSION_SPAM_REPORTS as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_EMAILS as d
WHERE s.email = d.email;

DELETE FROM SNAPSHOT.REDSHIFT.STATS_GUIDS as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.user_id = d.user_id;

-- STRIPE_SUBSCRIPTION_DISCOUNT -- no user_id or email data

-- SUBSCRIPTIONS -- no user_id or email data

-- SYNDICATED_ARTICLES -- no user_id or email data

-- SYNDICATED_ARTICLE_SLUGS -- no user_id or email data

-- SYNDICATED_GOOGLE_ANALYTICS_DATA -- no user_id or email data

DELETE FROM SNAPSHOT.REDSHIFT.USERS as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.user_id = d.user_id;

DELETE FROM SNAPSHOT.REDSHIFT.USERS_META_ACTIONS as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.user_id = d.user_id;

-- Deleting based on both user_id and email
DELETE FROM SNAPSHOT.REDSHIFT.USER_EMAIL_MAP as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.user_id = d.user_id;

DELETE FROM SNAPSHOT.REDSHIFT.USER_EMAIL_MAP as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_EMAILS as d
WHERE s.email = d.email;

DELETE FROM SNAPSHOT.REDSHIFT.USER_LOCALE as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.user_id = d.user_id;

DELETE FROM SNAPSHOT.REDSHIFT.USER_SUBSCRIPTION as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.user_id = d.user_id;

DELETE FROM SNAPSHOT.REDSHIFT.USER_SUBSCRIPTION_HISTORY as s
USING USER_DATA_DELETION_DB.USER_DATA_DELETION_SCHEMA.DELETED_USERS as d
WHERE s.user_id = d.user_id;

