version: 0.2
#https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

#####
# Builds flows and registers them with Prefect Cloud
#####

env:
  parameter-store:
    PREFECT_APIKEY: $PREFECT_APIKEY_PARAMETER_NAME


phases:
  build:
    commands:
      - 'prefect auth login --key $PREFECT_APIKEY'
      - 'python bin/register_flows.py'
