version: '3.1'
# TODO: This docker-compose file is unfinished.
services:
  prefect:
    build:
      dockerfile: .docker/app/Dockerfile
      context: .
    command:
      - "prefect"
      - "agent"
      - "local" # Start a local agent for local development. In production this would be "ecs".
      - "start"
      - "--agent-address"
      - "http://0.0.0.0:8080"
    ports:
      - '8080:8080'
    volumes:
      - ./src:/app
      - ~/.aws:/root/.aws
    env_file:
      - .env
    environment:
      - PREFECT__CLOUD__API=https://api.prefect.io
      - PREFECT__CLOUD__AGENT__LABELS=["local"]
      - PREFECT__CLOUD__AGENT__LEVEL=DEBUG
      - AWS_DEFAULT_REGION=us-east-1
      - RUN_TASK_KWARGS=foobar
