SELECT
    s.APPROVED_CORPUS_ITEM_EXTERNAL_ID as "ID",
    i.TOPIC as "TOPIC",
    i.PUBLISHER AS "PUBLISHER"
FROM "ANALYTICS"."DBT"."SCHEDULED_CORPUS_ITEMS" AS s
LEFT JOIN "ANALYTICS"."DBT"."CORPUS_ITEMS_UPDATED" AS i
ON s.APPROVED_CORPUS_ITEM_EXTERNAL_ID = i.APPROVED_CORPUS_ITEM_EXTERNAL_ID
WHERE s.SCHEDULED_SURFACE_ID = %(SCHEDULED_SURFACE_ID)s
AND i.TOPIC IS NOT NULL
AND s.IS_SYNDICATED
AND s.SCHEDULED_CORPUS_ITEM_SCHEDULED_AT BETWEEN DATEADD(day, %(MAX_AGE_DAYS)s, CURRENT_DATE) AND CURRENT_DATE
QUALIFY row_number() OVER (PARTITION BY s.APPROVED_CORPUS_ITEM_EXTERNAL_ID ORDER BY s.SCHEDULED_CORPUS_ITEM_SCHEDULED_AT DESC) = 1
ORDER BY s.SCHEDULED_CORPUS_ITEM_SCHEDULED_AT DESC
