{% set sql_engine = "snowflake" %}
{% set is_multi_statement = True %}

create TRANSIENT TABLE if not exists CURATED_FEED_ITEMS (
	CURATED_REC_ID VARCHAR(16777216),
	SNOWFLAKE_LOADED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP(),
	FEED_ID VARCHAR(16777216),
	RESOLVED_ID VARCHAR(16777216),
	PROSPECT_ID VARCHAR(16777216),
	QUEUED_ID VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	TIME_LIVE VARCHAR(16777216),
	TIME_ADDED VARCHAR(16777216),
	TIME_UPDATED VARCHAR(16777216)
);
truncate table curated_feed_items;
COPY INTO curated_feed_items
(CURATED_REC_ID, FEED_ID, RESOLVED_ID, PROSPECT_ID, QUEUED_ID, STATUS, TIME_LIVE, TIME_ADDED, TIME_UPDATED)
  FROM @airflow.mysql.airflow_stage/curated_feed_exports_aurora/curated_feed_items{{environment}}
  FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = '|' SKIP_HEADER = 0);
