
-- BEGIN: RAW.FIREHOSSE

DELETE FROM "RAW"."FIREHOSE"."AB_TEST_TRACK" as s
USING "ANALYTICS"."DBT_STAGING"."STG_ACCOUNT_DELETIONS" as d
WHERE s.EVENT.data:user_key = d.user_id
AND s.EVENT.data:user_key_type_id = 1;

DELETE FROM "RAW"."FIREHOSE"."ITEM_SESSION" as s
USING "ANALYTICS"."DBT_STAGING"."STG_ACCOUNT_DELETIONS" as d
WHERE s.EVENT.data:user_id = d.user_id;

-- TODO: PINPOINT

DELETE FROM "RAW"."FIREHOSE"."POCKET_V3_SEND" as s
USING "ANALYTICS"."DBT_STAGING"."STG_ACCOUNT_DELETIONS" as d
WHERE s.EVENT.data:user_id = d.user_id;

DELETE FROM "RAW"."FIREHOSE"."PREMIUM_SUBSCRIPTION_CREATED" as s
USING "ANALYTICS"."DBT_STAGING"."STG_ACCOUNT_DELETIONS" as d
WHERE s.EVENT.data:user_id = d.user_id;

DELETE FROM "RAW"."FIREHOSE"."PREMIUM_SUBSCRIPTION_ENDED" as s
USING "ANALYTICS"."DBT_STAGING"."STG_ACCOUNT_DELETIONS" as d
WHERE s.EVENT.data:user_id = d.user_id;

DELETE FROM "RAW"."FIREHOSE"."PREMIUM_SUBSCRIPTION_RENEWED" as s
USING "ANALYTICS"."DBT_STAGING"."STG_ACCOUNT_DELETIONS" as d
WHERE s.EVENT.data:user_id = d.user_id;

-- TODO: SENDGRID_EVENTS

DELETE FROM "RAW"."FIREHOSE"."USER_ACTION" as s
USING "ANALYTICS"."DBT_STAGING"."STG_ACCOUNT_DELETIONS" as d
WHERE s.EVENT.data:user_id = d.user_id;

DELETE FROM "RAW"."FIREHOSE"."USER_ITEM_TAGS_ADDED" as s
USING "ANALYTICS"."DBT_STAGING"."STG_ACCOUNT_DELETIONS" as d
WHERE s.EVENT.data:user_id = d.user_id;

DELETE FROM "RAW"."FIREHOSE"."USER_LIST_ITEM_CREATED" as s
USING "ANALYTICS"."DBT_STAGING"."STG_ACCOUNT_DELETIONS" as d
WHERE s.EVENT.data:user_id = d.user_id;

DELETE FROM "RAW"."FIREHOSE"."USER_TRACK_ADV" as s
USING "ANALYTICS"."DBT_STAGING"."STG_ACCOUNT_DELETIONS" as d
WHERE s.EVENT.data:user_id = d.user_id;

DELETE FROM "RAW"."FIREHOSE"."WEB_TRACK" as s
USING "ANALYTICS"."DBT_STAGING"."STG_ACCOUNT_DELETIONS" as d
WHERE s.EVENT.data:user_id = d.user_id;

