AWSTemplateFormatVersion: '2010-09-09'
Description: Test CircleCI OpenID Cloudformation

Mappings:
  VariablesMap:
    Pocket:
      ProdAccountId: '996905175585'
      DevAccountId: '410318598490'
      ProxyAccountId: '130841106477'

Conditions:
  IsProd: !Equals
    - !Ref 'AWS::AccountId'
    - '996905175585'
  IsDev: !Equals
    - !Ref 'AWS::AccountId'
    - '410318598490'
  IsAmplify: !Equals
    - !Ref 'AWS::AccountId'
    - '613003240892'
  IsProxy: !Equals
    - !Ref 'AWS::AccountId'
    - '130841106477'

Resources:

  CircleCIOpenIDProvider:
    Type: AWS::IAM::OIDCProvider
    Properties: 
      ClientIdList: 
        - f606ad14-9ec3-4f9f-a245-1739bb212b70
      ThumbprintList: 
        - 9e99a48a9960b14926bb7f3b02e22da2b0ab7280
      Url: https://oidc.circleci.com/org/f606ad14-9ec3-4f9f-a245-1739bb212b70

  CircleCIPrefectOpenIDPolicy:
    Metadata:
      Notes1: CircleCI IAM policy for Prefect Infrastructure Deployment
    Type: AWS::IAM::ManagedPolicy
    Condition: IsProd
    Properties:
      Description: Policy which grants the CircleCI OpenID Role the right to deploy Prefect Resources
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 
            - "logs:Create*"
            - "logs:Describe*"
            - "logs:List*"
            - "secretsmanager:Describe*"
            - "ecs:CreateCluster"
            - "ecs:Describe*"
            - "ecs:RegisterTaskDefinition"
            Resource:
              - '*'
          - Effect: Allow
            Action: 
            - "secretsmanager:Get*"
            Resource:
              - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:Shared/DockerHub*"
              - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:dpt/*"
          - Effect: Allow
            Action: 
            - "iam:Create*"
            - "iam:Put*"
            - "iam:Get*"
            - "iam:Pass*"
            - "iam:List*"
            - "iam:Delete*"
            - "iam:Attach*"
            Resource:
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/prefect-*"
              - !Sub "arn:aws:iam::${AWS::AccountId}:policy/prefect-*"
          - Effect: Allow
            Action: 
            - "ecs:Delete*"
            - "ecs:Put*"
            Resource:
              - !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/prefect-*"
              - !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/dpt-*"
          - Effect: Allow
            Action: 
            - "ecs:Start*"
            - "ecs:Stop*"
            - "ecs:Run*"
            - "ecs:*Service*"
            Resource:
              - '*'
            Condition:
              ArnLike:
                ecs:cluster": 
                - "arn:aws:ecs:{AWS::Region}:${AWS::AccountId}:cluster/prefect-*"
                - "arn:aws:ecs:{AWS::Region}:${AWS::AccountId}:cluster/dpt-*"
  
  CircleCIPrefectOpenIDRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref CircleCIOpenIDProvider
            Condition:
              StringEquals:
                oidc.circleci.com/org/f606ad14-9ec3-4f9f-a245-1739bb212b70:aud: f606ad14-9ec3-4f9f-a245-1739bb212b70
              ForAnyValue:StringLike:
                oidc.circleci.com/org/f606ad14-9ec3-4f9f-a245-1739bb212b70:sub: org/f606ad14-9ec3-4f9f-a245-1739bb212b70/project/83d96155-1fc1-4b8e-b49e-6914d84f521d/user/*

      ManagedPolicyArns:
        - !If 
          - IsProd
          - !Ref CircleCIPrefectOpenIDPolicy
          - !Sub arn:aws:iam::${AWS::AccountId}:policy/CircleCIPrefectOpenIDRole
      RoleName: CircleCIPrefectOpenIDRole

  