[tool.poetry]
name = "common-utils"
version = "0.1.0"
description = "Shared modules for prefect flow development and deployment"
authors = ["Braun <breyes@mozilla.com>"]
license = "Apache-2.0"
readme = "README.md"
packages = [{include = "common", from = 'src'}]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.scripts]
deploy-cli = 'common.deployment.cli:main'

[tool.poetry.group.dev.dependencies]
prefect = "^2.8.2"
prefect-aws = "^0.2.4"
pytest = "^7.2.1"
black = "^23.1.0"
pytest-cov = "^4.0.0"
s3fs = "^2023.1.0"
greenlet = "^2.0.2"
moto = {extras = ["sts"], version = "^4.1.3"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# this exists for unit testing
[tool.prefect.envs.base]
python_version = "3.10"
dockerfile_path=".docker/main/Dockerfile"